### ISSUE TITLE
Unnecessary warning

### ISSUE THREAD

**Issue by rojcyk** [Vasfed/csso-rails#26]
Hey, I'm using Node.js via ExecJS and it gives me this error.

`You're using ExecJS::ExternalRuntime, did you forget to add therubyracer or other execjs runtime to gemfile?`

Can we disable the warning since ExecJS [will raise an error](https://github.com/rails/execjs/blob/master/lib/execjs/runtimes.rb#L56) if no engine is found?

**Comment by rojcyk** [comment]
Or an option to silence it would be nice! :]

**Comment by dalibor** [comment]
:+1:
