### ISSUE TITLE
csso v5 upgrade

### ISSUE THREAD

**Issue by gremz** [Vasfed/csso-rails#35]
Can we get this gem updated to support the latest csso v5 library? Thanks.

**Comment by Vasfed** [comment]
Updated csso in master, passes tests (those are more a smoke test in fact). Can you test it and let me know if it is ok to release?

**Comment by gremz** [comment]
Thanks for getting that out. It is working for me locally for a few simple cases I use it for

**Comment by gremz** [comment]
@Vasfed any chance we could get these changes added to a tag and pushed to Rubygems? Thanks!

**Comment by Vasfed** [comment]
Released v1.0
